name: master_utility
description: All-in-one utility solution with Size, Navigation, Image Picker, Date Time, Auto Size Text, Toast, Email, Log, Dialog, Cache Image, Validation, API and Shared Preferences.
version: 0.0.2
homepage: https://github.com/webelightsolutions/flutter-master-utility.git

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.8.2
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.4
  dio: ^4.0.6
  dio_http_formatter: ^2.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_jailbreak_detection: ^1.10.0
  import_sorter: ^4.6.0
  flutter_cache_manager: ^3.3.1
  image_picker_platform_interface: ^2.9.1
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
